# Generated by Django 4.1.3 on 2022-11-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.EmailField(max_length=15)),
                ('correo', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
    ]
